api:
  dashboard: true
  insecure: false

ping: {}

certificatesResolvers:
  myresolver:
    acme:
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    exposedByDefault: false

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true


log:
  level: INFO

accessLog:
  filePath: "/traefik-logs/access.log"
  bufferingSize: 128
  filters:
    retryAttempts: true
    statusCodes:
      - "400-599"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        Authorization: drop

tls:
  options:
    default:
      minVersion: VersionTLS13

metrics:
  prometheus: 
    addRoutersLabels: true


